lms/academy/urls.py
from django.urls import path, include, path
from rest_framework.routers import DefaultRouter
from django.contrib.auth import views as auth_views
from . import views

router = DefaultRouter()
router.register(r'products', views.ProductViewSet)
router.register(r'lessons', views.LessonViewSet)
router.register(r'user-lessons', views.UserLessonViewSet)

urlpatterns = [
    path('api/user-lessons/', views.UserLessonListView.as_view(), name='user-lesson-list'),
    path('api/products/<int:product_id>/lessons/', views.ProductLessonListView.as_view(), name='product-lesson-list'),
    path('api/product-stats/', views.ProductStatsView.as_view(), name='product-stats'),
    path('', views.index, name='index'),
    path('', include(router.urls)),
    path('accounts/profile/', views.profile, name='profile'),
    path('create/', views.create_product, name='create_product'),
    path('edit/<int:pk>/', views.edit_product, name='edit_product'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    # path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('login/', views.login_view, name='login'),
]

lms/lms/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf import settings
from django.conf.urls.static import static


schema_view = get_schema_view(
    openapi.Info(
        title="Academy API",
        default_version='v1',
        description="Спецификация по работе с API для Academy",
        terms_of_service="#",
        contact=openapi.Contact(email="demetrius.belkin@gmail.com"),
        license=openapi.License(name="Free"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('', include('academy.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lms/academy/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    name = models.CharField(max_length=255)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField(default='Описание отсутствует')
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    image = models.ImageField(upload_to='product_images/', blank=True, null=True)
    duration = models.IntegerField(default=0)
    students = models.ManyToManyField(User, related_name='enrolled_courses', blank=True)

    def __str__(self):
        return self.name

    objects = models.Manager()


class Enrollment(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.student.username} - {self.product.name}"


class Lesson(models.Model):
    product = models.ForeignKey(Product, null=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    video_url = models.URLField()
    duration_seconds = models.IntegerField()
    products = models.ManyToManyField(Product, related_name='lessons')

    objects = models.Manager()


class UserLesson(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    viewed = models.BooleanField(default=False)
    view_time_seconds = models.IntegerField(default=0)
    video_progress = models.FloatField(default=0.0)

    objects = models.Manager()

    def update_video_progress(self, new_progress):
        self.video_progress = new_progress
        self.save()
        self.mark_as_viewed()

    def mark_as_viewed(self):
        if self.video_progress >= 80:
            self.viewed = True
        else:
            self.viewed = False
        self.save()


class UserAccess(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    objects = models.Manager()

    def __str__(self):
        # noinspection PyUnresolvedReferences
        return f"{self.user.username} - {self.product.name}"

lms/academy/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'image']

lms/academy/views.py
from django.shortcuts import render, redirect, get_object_or_404
from rest_framework import generics, viewsets
from django.http import JsonResponse
from .models import Lesson, UserLesson, Product, UserAccess, Enrollment
from .forms import ProductForm
from django.contrib.auth import authenticate, login
from .serializers import ProductSerializer, LessonSerializer, UserLessonSerializer, ProductStatsSerializer

from django.db.models import Sum


class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer


class LessonViewSet(viewsets.ModelViewSet):
    queryset = Lesson.objects.all()
    serializer_class = LessonSerializer


class UserLessonViewSet(viewsets.ModelViewSet):
    queryset = UserLesson.objects.all()
    serializer_class = UserLessonSerializer


class UserLessonListView(generics.ListAPIView):
    serializer_class = UserLessonSerializer

    def get_queryset(self):
        user = self.request.user
        return UserLesson.objects.filter(user=user)


class ProductLessonListView(generics.ListAPIView):
    serializer_class = UserLessonSerializer

    def get_queryset(self):
        user = self.request.user
        product_id = self.kwargs['product_id']
        return UserLesson.objects.filter(user=user, lesson__product_id=product_id)


class ProductStatsView(generics.ListAPIView):
    serializer_class = ProductStatsSerializer

    def get_queryset(self):
        user = self.request.user
        products = Product.objects.all()
        queryset = []
        for product in products:
            access_count = UserAccess.objects.filter(product=product).count()
            lesson_count = UserLesson.objects.filter(lesson__product=product, user=user).count()
            total_watch_time = UserLesson.objects.filter(lesson__product=product,
                                                         user=user).aggregate(Sum('watch_time'))['watch_time__sum']
            total_users = UserAccess.objects.filter(product=product).count()
            purchase_percentage = (access_count / total_users) * 100 if total_users > 0 else 0

            queryset.append({
                'product_id': product.id,
                'product_name': product.name,
                'lesson_count': lesson_count,
                'total_watch_time': total_watch_time,
                'total_users': total_users,
                'purchase_percentage': purchase_percentage,
            })
        return queryset


def index(request):
    products = Product.objects.all()
    lessons = Lesson.objects.all()
    user_lessons = UserLesson.objects.all()
    user_access = UserAccess.objects.all()

    context = {
        'products': products,
        'lessons': lessons,
        'user_lessons': user_lessons,
        'user_access': user_access,
    }

    return render(request, 'index.html', context)


def profile(request):
    user = request.user

    context = {
        'user': user,
    }

    return render(request, 'profile.html', context)


def create_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('product_list')
    else:
        form = ProductForm()
    return render(request, 'create_product.html', {'form': form})


def edit_product(request, pk):
    product = Product.objects.get(pk=pk)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('product_list')
    else:
        form = ProductForm(instance=product)
    return render(request, 'edit_product.html', {'form': form})


def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    lessons = Lesson.objects.filter(product=product)
    return render(request, 'product_detail.html', {'product': product, 'lessons': lessons})


def login_view(request):
    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            return JsonResponse({'success': False, 'error_message': 'Неверные учетные данные'})

    return render(request, 'login.html')


def product_detail(request, product_id):
    product = Product.objects.get(id=product_id)

    enrollment, created = Enrollment.objects.get_or_create(product=product, student=request.user)

    enrolled_students = Enrollment.objects.filter(product=product).count()

    context = {
        'product': product,
        'enrollment': enrollment,
        'enrolled_students': enrolled_students,
    }

    return render(request, 'product_detail.html', context)

lms/academy/templates/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dmitriy Belkin">
    <title>{% block title %}Academy{% endblock %}</title>
    {% load static %}
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.5.0/dist/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<header class="p-3 text-bg-dark border-bottom">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                    <img src="{% static 'img/logo.png' %}" width="50" height="52">
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="/" class="nav-link px-2 text-secondary">Главная</a></li>
                    <li><a href="#" class="nav-link px-2 text-white">О нас</a></li>
                    <li><a href="#" class="nav-link px-2 text-white">Курсы</a></li>
                    <li><a href="#" class="nav-link px-2 text-white">Цены</a></li>
                    <li><a href="#" class="nav-link px-2 text-white">Контакты</a></li>
                </ul>

                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                    <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Поиск..." aria-label="Search">
                </form>

                <div class="text-end">
                    <button type="button" class="btn btn-outline-light me-2" data-bs-toggle="modal" data-bs-target="#loginModal">Войти</button>
                    <button type="button" class="btn btn-warning">Регистрация</button>
                </div>
            </div>
        </div>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

<!--Footer-->
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                <img src="{% static 'img/logo.png' %}" width="50" height="52">
            </a>
            <span class="mb-3 mb-md-0 text-body-secondary">© 2023 Belkin Dmitriy</span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-body-secondary" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
                    <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
                </svg></a></li>
            <li class="ms-3"><a class="text-body-secondary" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                    <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
                </svg></a></li>
            <li class="ms-3 me-3 me-4"><a class="text-body-secondary" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
                </svg></a></li>
        </ul>
  </footer>

<!--    Авторизация-->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModalLabel">Вход</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'login' %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="username" class="form-label">Логин:</label>
                        <input type="text" class="form-control" id="username" name="username" required>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Пароль:</label>
                        <input type="password" class="form-control" id="password" name="password" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Войти</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!--    <script src="{% static 'js/scripts.js' %}"></script>-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>

<script>
document.querySelector('form').addEventListener('submit', async (e) => {
    e.preventDefault();

    const username = document.querySelector('#username').value;
    const password = document.querySelector('#password').value;

    const response = await fetch("{% url 'login' %}", {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': csrf_token
        },
        body: JSON.stringify({ username, password })
    });

    if (response.ok) {
        const data = await response.json();

        if (data.success) {
    const loginModal = new bootstrap.Modal(document.getElementById('loginModal'));
    loginModal.hide();

    location.reload();
}

        } else {
            const errorMessageElement = document.querySelector('#error-message');
            errorMessageElement.textContent = data.error_message;
            errorMessageElement.style.display = 'block';
        }
    } else {
        console.error('Authentication failed');
    }
});
</script>
</body>
</html>

lms/academy/templates/index.html
{% extends "base.html" %}
{% block title %} Academy {% endblock %}
{% block content %}
        <section class="py-5 text-center container">
            <div class="row py-lg-5">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <h1 class="fw-light">Academy LMS on Django</h1>
                    <p class="lead text-body-secondary">Огромное спасибо за такое интересное задание! <br/> За эту бессонную ночь я столько всего нового изучил и не удержался, захотел сделать немного больше, чем требовалось. Собственно, есть swagger и фронт, а для быстрой верстки использую Bootstrap 5 (но его тоже пришлось изучать). <br/> Шутки про то, как тестировщик написал сайт - приветствуются!</p>
                    <p>
                        <a href="#" class="btn btn-primary my-2">Ты большой молодец!</a>
                        <a href="#" class="btn btn-secondary my-2">Ты большой молодец!</a>
                    </p>
                </div>
            </div>
        </section>

<!--Карточки курсов-->
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <h2>Курсы</h2>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for product in products %}
            <div class="col">
                <div class="card shadow-sm h-100 overflow-hidden">
    {% if product.image %}
    <img src="{{ product.image.url }}" class="bd-placeholder-img card-img-top" width="100%" height="225">
    {% else %}
    <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
        <title>Placeholder</title>
        <rect width="100%" height="100%" fill="#55595c"></rect>
        <text x="30%" y="50%" fill="#eceeef" dy=".3em">Картинка отсутствует</text>
    </svg>
    {% endif %}
    <div class="card-body d-flex flex-column">
        <h3>{{ product.name }}</h3>
        <br/>
        <small class="text-body-secondary">Цена: {{ product.price }}</small>
        <br/><br/>
        <p class="card-text">{{ product.description }}</p>
        <small class="text-body-secondary mb-2">Длительность: {{ product.duration }} минут</small>

        <div class="mt-auto">
            <div class="btn-group">
                <a href="{% url 'product_detail' product.id %}" class="btn btn-sm btn-outline-secondary">Подробнее</a>
                {% if user.is_authenticated and user.is_staff %}
                <button type="button" class="btn btn-sm btn-outline-secondary">Редактировать</button>
                {% endif %}
            </div>
        </div>
    </div>
</div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

lms/academy/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Вход</div>
                <div class="card-body">
                    {% if messages %}
                    <div class="alert alert-danger">
                        <ul>
                            {% for message in messages %}
                            <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="username" class="form-label">Логин:</label>
                            <input type="text" class="form-control" id="username" name="username" required>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Пароль:</label>
                            <input type="password" class="form-control" id="password" name="password" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Войти</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

lms/academy/templates/product_detail.html
{% extends "base.html" %}

{% block title %} {{product.name}} - подробнее {% endblock %}

{% block content %}
<!--Breadcrumb-->
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Главная</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ product.name }}</li>
  </ol>
</nav>

<!--Информация по курсам-->
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>{{ product.name }}</h1>
        <small>Студентов: {{ enrolled_students }}</small>
      {% if product.image %}
        <img src="{{ product.image.url }}" class="bd-placeholder-img card-img-top" width="100%" height="525">
      {% else %}
        <svg class="bd-placeholder-img card-img-top" width="100%" height="525" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
          <rect width="100%" height="100%" fill="#55595c"></rect>
          <text x="30%" y="50%" fill="#eceeef" dy=".3em">Картинка отсутствует</text>
        </svg>
      {% endif %}
      <p>Количество уроков: {{ product.lessons.count }}</p>
      <h3>Описание курса:</h3>
      <p>{{ product.description }}</p>
      <p>Цена: {{ product.price }}</p>
      <p>Длительность: {{ product.duration }} минут</p>

<h3>Список уроков:</h3>
<div class="list-group">
    <div id="accordion">
        {% for lesson in product.lessons.all %}
            <div class="card" style="cursor: pointer;">
                <div class="card-header" id="heading{{ lesson.id }}">
                    <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Название урока: {{ lesson.title }}</h5>
                    <small>
                        {% if lesson.userlesson_set.first.viewed %}
                            <span class="viewed">Просмотрено</span>
                        {% else %}
                            <span class="not-viewed">Не просмотрено</span>
                        {% endif %}
                    </small>
                    </div>
                    <br/>
                    <small>
                        {% if lesson.userlesson_set.first.viewed %}
                            <span>Прогресс: {{ lesson.userlesson_set.first.video_progress }}%</span>
                        {% else %}
                            <span>Вы еще не проходили этот урок</span>
                        {% endif %}
                    </small>
                        <!--<small>Пройден: {% if lesson.userlesson_set.first.viewed %}Да{% else %}Нет{% endif %}</small>-->
                        <button class="btn btn-link {% if forloop.first %}collapsed{% endif %}" data-toggle="collapse" data-target="#collapse{{ lesson.id }}" aria-expanded="{% if forloop.first %}true{% else %}false{% endif %}" aria-controls="collapse{{ lesson.id }}"></button>

                </div>
                <div id="collapse{{ lesson.id }}" class="collapse {% if forloop.first %}show{% endif %}" aria-labelledby="heading{{ lesson.id }}" data-parent="#accordion">
                    <div class="card-body">
                        <p>Описание: {{ lesson.description }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>





    </div>
  </div>
</div>
<script>
    // Получаем все элементы строки урока и добавляем обработчик клика
    const lessonRows = document.querySelectorAll('.card');
    lessonRows.forEach((row) => {
        row.addEventListener('click', () => {
            const button = row.querySelector('button[data-toggle="collapse"]');
            if (button) {
                // Если найдена кнопка внутри строки, имитируем клик по ней
                button.click();
            }
        });
    });
</script>

{% endblock %}

lms/academy/templates/profile.html
<!DOCTYPE html>
<html>
<head>
    <title>Профиль пользователя</title>
</head>
<body>
    <h1>Профиль пользователя</h1>
    {% if user.is_authenticated %}
        <p>Привет, {{ user.username }}!</p>

    {% else %}
        <p>Пожалуйста, войдите в систему.</p>
    {% endif %}

</body>
</html>

lms/academy/templates/static_urls.html
<script type="text/javascript">
    var scriptUrl = "{% get_static_prefix %}script.js";
    var styleUrl = "{% get_static_prefix %}style.css";
</script>